#!/usr/bin/perl
use Modern::Perl;
use AnyEvent;
use AnyEvent::Socket;

my $cv = AnyEvent->condvar;

tcp_connect localhost => 8889, sub {
   my ($fh) = @_
      or return $cv->send;
   # enjoy your filehandle
   syswrite $fh, "hello\015\012";

   my $response;

   # register a read watcher
   my $read_watcher; $read_watcher = AnyEvent->io (
      fh   => $fh,
      poll => "r",
      cb   => sub {
         my $len = sysread $fh, $response, 1024, length $response;
 
         if ($len <= 0) {
            # we are done, or an error occured, lets ignore the latter
            undef $read_watcher; # no longer interested
            $cv->send ($response); # send results
         }
      },
   );

};

$cv->recv;
